from django.urls import path
from . import views



urlpatterns = [
    path('', views.HOME_view, name='home-page'),
    path('LOGIN/LOGED/', views.LOGED_view),
    path('LOGIN/REGISTER/', views.REGISTER_view),
    path('LOGIN/REGISTER/SUCCESS/', views.success_view),
    path('USERS/ADMIN/', views.ADMIN_view),
    path('USERS/ADMIN/SETTINGS/', views.ADMIN_SETTINGS_view),
    path('USERS/ADMIN/USERS/', views.ADMIN_USERS_view),
    path('USERS/ADMIN/USERS/TEACHERS/CLASS/', views.ADMIN_USERS_TEACHERS_CLASS_view),
    path('USERS/ADMIN/USERS/TEACHERS/CLASS/STUDENTS/', views.ADMIN_USERS_TEACHERS_CLASS_STUDENTS_view),
    path('USERS/STUDENT/', views.STUDENT_view),
    path('USERS/STUDENT/ALPHABET/', views.STUDENT_ALPHABET_view),
    path('USERS/STUDENT/BOOKS/', views.STUDENT_BOOKS_view),
    path('USERS/STUDENT/TEST/', views.STUDENT_TEST_view),
    path('USERS/STUDENT/WORDS/', views.STUDENT_WORDS_view),
    path('USERS/TEACHER/', views.TEACHER_view),


]


'''
path('', views.HOME_view, name='home-page'),

    path('LOGIN/LOGED/', views.LOGED_view),
    path('LOGIN/REGISTER/', views.REGISTER_view),
    path('LOGIN/REGISTER/SUCCESS/', views.success_view),



    path('USERS/ADMIN/', views.ADMIN_view),

    path('USERS/ADMIN/DATA/', views.ADMIN_DATA_view),

    path('USERS/ADMIN/DATA_BASE/', views.ADMIN_DATA_BASE_view),
    path('USERS/ADMIN/DATA_BASE/BOOKS/', views.ADMIN_DATA_BASE_BOOKS_view),
    path('USERS/ADMIN/DATA_BASE/PIC/', views.ADMIN_DATA_BASE_PIC_view),
    path('USERS/ADMIN/DATA_BASE/WORDS/', views.ADMIN_DATA_BASE_WORDS_view),

    #path('USERS/ADMIN/RETING/', views.ADMIN_RETING_view),

    path('USERS/ADMIN/SETTINGS/', views.ADMIN_SETTINGS_view),
    path('USERS/ADMIN/SETTINGS/DISPLAY/', views.ADMIN_SETTINGS_DISPLAY_view),
    path('USERS/ADMIN/SETTINGS/SITE_SETTINGS', views.ADMIN_SETTINGS_SITE_SETTINGS_view),

    path('USERS/ADMIN/USERS/', views.ADMIN_USERS_view),
    path('USERS/ADMIN/USERS/TEACHERS/', views.ADMIN_USERS_TEACHERS_view),
    path('USERS/ADMIN/USERS/TEACHERS/CLASS/', views.ADMIN_USERS_TEACHERS_CLASS_view),
    path('USERS/ADMIN/USERS/TEACHERS/CLASS/STUDENTS/', views.ADMIN_USERS_TEACHERS_CLASS_STUDENTS_view),

    
    path('USERS/STUDENT/', views.STUDENT_view),
    path('USERS/STUDENT/ALPHABET/', views.STUDENT_ALPHABET_view),
    path('USERS/STUDENT/BOOKS/', views.STUDENT_BOOKS_view),
    path('USERS/STUDENT/TEST/', views.STUDENT_TEST_view),
    path('USERS/STUDENT/WORDS/', views.STUDENT_WORDS_view),

    
    path('USERS/TEACHER/', views.TEACHER_view),
    path('USERS/TEACHER/CLASS/', views.TEACHER_CLASS_view),

    path('USERS/TEACHER/CLASS/STUDENT_REGISTRATION/', views.TEACHER_STUDENT_REGISTRATION_view),
    path('USERS/TEACHER/CLASS/STUDENT_REGISTRATION/REGISTER_SUCCESS/', views.TEACHER_STUDENT_REGISTRATION_REGISTER_SUCCESS_view),

    path('USERS/TEACHER/CLASS/STUDENTS/', views.TEACHER_CLASS_STUDENTS_view),
    path('USERS/TEACHER/CLASS/STUDENTS/STUDENT/', views.TEACHER_CLASS_STUDENTS_STUDENT_view),
    path('USERS/TEACHER/CLASS/STUDENTS/STUDENT/DISPLAY/', views.TEACHER_CLASS_STUDENTS_STUDENT_DISPLAY_view),
    path('USERS/TEACHER/CLASS/STUDENTS/STUDENT/STUDENT_DATA/', views.TEACHER_CLASS_STUDENTS_STUDENT_DATA_view),
    path('USERS/TEACHER/CLASS/STUDENTS/STUDENT/STUDENT_PAGE/', views.TEACHER_CLASS_STUDENTS_STUDENT_PAGE_view),



'''
